INCLUDE_DIR = /home/satya-tt0492/onnxruntime-linux-x64-1.20.0/include
LIB_DIR = /home/satya-tt0492/onnxruntime-linux-x64-1.20.0/lib

my_program: comparison.cpp
		g++ comparison.cpp -I $(INCLUDE_DIR) -L $(LIB_DIR) -lonnxruntime -lsndfile -lsamplerate -o rfftcompare